// <auto-generated />
using EF_project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_project.Migrations
{
    [DbContext(typeof(EFContext))]
    partial class EFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_project.Models.Categories", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "T-Shirt"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Jeans"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Hoodie"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Jacket"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Suit"
                        });
                });

            modelBuilder.Entity("EF_project.Models.Favorites", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("EF_project.Models.Products", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Price = 19,
                            ProductName = "Black T-Shirt"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Price = 15,
                            ProductName = "White T-Shirt"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Price = 17,
                            ProductName = "Blue T-Shirt"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            Price = 18,
                            ProductName = "Gray T-Shirt"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            Price = 20,
                            ProductName = "Red T-Shirt"
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 1,
                            Price = 21,
                            ProductName = "Green T-Shirt"
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 1,
                            Price = 22,
                            ProductName = "Yellow T-Shirt"
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 1,
                            Price = 19,
                            ProductName = "Purple T-Shirt"
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 1,
                            Price = 23,
                            ProductName = "Orange T-Shirt"
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 1,
                            Price = 18,
                            ProductName = "Pink T-Shirt"
                        },
                        new
                        {
                            ProductId = 31,
                            CategoryId = 1,
                            Price = 24,
                            ProductName = "Navy Blue T-Shirt"
                        },
                        new
                        {
                            ProductId = 32,
                            CategoryId = 1,
                            Price = 20,
                            ProductName = "Sky Blue T-Shirt"
                        },
                        new
                        {
                            ProductId = 33,
                            CategoryId = 1,
                            Price = 21,
                            ProductName = "Maroon T-Shirt"
                        },
                        new
                        {
                            ProductId = 34,
                            CategoryId = 1,
                            Price = 19,
                            ProductName = "Beige T-Shirt"
                        },
                        new
                        {
                            ProductId = 35,
                            CategoryId = 1,
                            Price = 22,
                            ProductName = "Olive T-Shirt"
                        },
                        new
                        {
                            ProductId = 36,
                            CategoryId = 1,
                            Price = 25,
                            ProductName = "Turquoise T-Shirt"
                        },
                        new
                        {
                            ProductId = 37,
                            CategoryId = 1,
                            Price = 20,
                            ProductName = "Teal T-Shirt"
                        },
                        new
                        {
                            ProductId = 38,
                            CategoryId = 1,
                            Price = 23,
                            ProductName = "Lime T-Shirt"
                        },
                        new
                        {
                            ProductId = 39,
                            CategoryId = 1,
                            Price = 19,
                            ProductName = "Coral T-Shirt"
                        },
                        new
                        {
                            ProductId = 40,
                            CategoryId = 1,
                            Price = 21,
                            ProductName = "Magenta T-Shirt"
                        },
                        new
                        {
                            ProductId = 41,
                            CategoryId = 1,
                            Price = 22,
                            ProductName = "Brown T-Shirt"
                        },
                        new
                        {
                            ProductId = 42,
                            CategoryId = 1,
                            Price = 18,
                            ProductName = "Charcoal T-Shirt"
                        },
                        new
                        {
                            ProductId = 43,
                            CategoryId = 1,
                            Price = 24,
                            ProductName = "Silver T-Shirt"
                        },
                        new
                        {
                            ProductId = 44,
                            CategoryId = 1,
                            Price = 26,
                            ProductName = "Gold T-Shirt"
                        },
                        new
                        {
                            ProductId = 45,
                            CategoryId = 1,
                            Price = 20,
                            ProductName = "Cyan T-Shirt"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Price = 49,
                            ProductName = "Slim Fit Blue Jeans"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 2,
                            Price = 54,
                            ProductName = "Regular Fit Black Jeans"
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            Price = 59,
                            ProductName = "Skinny Fit Gray Jeans"
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2,
                            Price = 44,
                            ProductName = "Relaxed Fit Light Blue Jeans"
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 2,
                            Price = 49,
                            ProductName = "Straight Fit Dark Blue Jeans"
                        },
                        new
                        {
                            ProductId = 46,
                            CategoryId = 2,
                            Price = 50,
                            ProductName = "Slim Fit Dark Gray Jeans"
                        },
                        new
                        {
                            ProductId = 47,
                            CategoryId = 2,
                            Price = 55,
                            ProductName = "Regular Fit Navy Jeans"
                        },
                        new
                        {
                            ProductId = 48,
                            CategoryId = 2,
                            Price = 60,
                            ProductName = "Skinny Fit Black Jeans"
                        },
                        new
                        {
                            ProductId = 49,
                            CategoryId = 2,
                            Price = 45,
                            ProductName = "Relaxed Fit Beige Jeans"
                        },
                        new
                        {
                            ProductId = 50,
                            CategoryId = 2,
                            Price = 48,
                            ProductName = "Straight Fit Light Gray Jeans"
                        },
                        new
                        {
                            ProductId = 51,
                            CategoryId = 2,
                            Price = 52,
                            ProductName = "Slim Fit White Jeans"
                        },
                        new
                        {
                            ProductId = 52,
                            CategoryId = 2,
                            Price = 56,
                            ProductName = "Regular Fit Olive Jeans"
                        },
                        new
                        {
                            ProductId = 53,
                            CategoryId = 2,
                            Price = 62,
                            ProductName = "Skinny Fit Dark Blue Jeans"
                        },
                        new
                        {
                            ProductId = 54,
                            CategoryId = 2,
                            Price = 47,
                            ProductName = "Relaxed Fit Brown Jeans"
                        },
                        new
                        {
                            ProductId = 55,
                            CategoryId = 2,
                            Price = 51,
                            ProductName = "Straight Fit Sky Blue Jeans"
                        },
                        new
                        {
                            ProductId = 56,
                            CategoryId = 2,
                            Price = 49,
                            ProductName = "Slim Fit Light Blue Jeans"
                        },
                        new
                        {
                            ProductId = 57,
                            CategoryId = 2,
                            Price = 53,
                            ProductName = "Regular Fit Indigo Jeans"
                        },
                        new
                        {
                            ProductId = 58,
                            CategoryId = 2,
                            Price = 61,
                            ProductName = "Skinny Fit Charcoal Jeans"
                        },
                        new
                        {
                            ProductId = 59,
                            CategoryId = 2,
                            Price = 46,
                            ProductName = "Relaxed Fit Stone Wash Jeans"
                        },
                        new
                        {
                            ProductId = 60,
                            CategoryId = 2,
                            Price = 50,
                            ProductName = "Straight Fit Vintage Blue Jeans"
                        },
                        new
                        {
                            ProductId = 61,
                            CategoryId = 2,
                            Price = 54,
                            ProductName = "Slim Fit Washed Black Jeans"
                        },
                        new
                        {
                            ProductId = 62,
                            CategoryId = 2,
                            Price = 57,
                            ProductName = "Regular Fit Classic Blue Jeans"
                        },
                        new
                        {
                            ProductId = 63,
                            CategoryId = 2,
                            Price = 63,
                            ProductName = "Skinny Fit Distressed Jeans"
                        },
                        new
                        {
                            ProductId = 64,
                            CategoryId = 2,
                            Price = 48,
                            ProductName = "Relaxed Fit Ripped Jeans"
                        },
                        new
                        {
                            ProductId = 65,
                            CategoryId = 2,
                            Price = 52,
                            ProductName = "Straight Fit Faded Jeans"
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3,
                            Price = 39,
                            ProductName = "Black Hoodie"
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3,
                            Price = 34,
                            ProductName = "Gray Hoodie"
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 3,
                            Price = 37,
                            ProductName = "Navy Hoodie"
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 3,
                            Price = 35,
                            ProductName = "Green Hoodie"
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 3,
                            Price = 40,
                            ProductName = "Red Hoodie"
                        },
                        new
                        {
                            ProductId = 66,
                            CategoryId = 3,
                            Price = 38,
                            ProductName = "White Hoodie"
                        },
                        new
                        {
                            ProductId = 67,
                            CategoryId = 3,
                            Price = 36,
                            ProductName = "Blue Hoodie"
                        },
                        new
                        {
                            ProductId = 68,
                            CategoryId = 3,
                            Price = 41,
                            ProductName = "Yellow Hoodie"
                        },
                        new
                        {
                            ProductId = 69,
                            CategoryId = 3,
                            Price = 37,
                            ProductName = "Orange Hoodie"
                        },
                        new
                        {
                            ProductId = 70,
                            CategoryId = 3,
                            Price = 39,
                            ProductName = "Purple Hoodie"
                        },
                        new
                        {
                            ProductId = 71,
                            CategoryId = 3,
                            Price = 35,
                            ProductName = "Beige Hoodie"
                        },
                        new
                        {
                            ProductId = 72,
                            CategoryId = 3,
                            Price = 42,
                            ProductName = "Brown Hoodie"
                        },
                        new
                        {
                            ProductId = 73,
                            CategoryId = 3,
                            Price = 36,
                            ProductName = "Olive Hoodie"
                        },
                        new
                        {
                            ProductId = 74,
                            CategoryId = 3,
                            Price = 40,
                            ProductName = "Teal Hoodie"
                        },
                        new
                        {
                            ProductId = 75,
                            CategoryId = 3,
                            Price = 37,
                            ProductName = "Cyan Hoodie"
                        },
                        new
                        {
                            ProductId = 76,
                            CategoryId = 3,
                            Price = 38,
                            ProductName = "Dark Gray Hoodie"
                        },
                        new
                        {
                            ProductId = 77,
                            CategoryId = 3,
                            Price = 39,
                            ProductName = "Sky Blue Hoodie"
                        },
                        new
                        {
                            ProductId = 78,
                            CategoryId = 3,
                            Price = 35,
                            ProductName = "Lime Hoodie"
                        },
                        new
                        {
                            ProductId = 79,
                            CategoryId = 3,
                            Price = 41,
                            ProductName = "Coral Hoodie"
                        },
                        new
                        {
                            ProductId = 80,
                            CategoryId = 3,
                            Price = 38,
                            ProductName = "Maroon Hoodie"
                        },
                        new
                        {
                            ProductId = 81,
                            CategoryId = 3,
                            Price = 36,
                            ProductName = "Charcoal Hoodie"
                        },
                        new
                        {
                            ProductId = 82,
                            CategoryId = 3,
                            Price = 42,
                            ProductName = "Silver Hoodie"
                        },
                        new
                        {
                            ProductId = 83,
                            CategoryId = 3,
                            Price = 44,
                            ProductName = "Gold Hoodie"
                        },
                        new
                        {
                            ProductId = 84,
                            CategoryId = 3,
                            Price = 39,
                            ProductName = "Turquoise Hoodie"
                        },
                        new
                        {
                            ProductId = 85,
                            CategoryId = 3,
                            Price = 37,
                            ProductName = "Magenta Hoodie"
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 4,
                            Price = 99,
                            ProductName = "Bomber Jacket"
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 4,
                            Price = 149,
                            ProductName = "Leather Jacket"
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 4,
                            Price = 79,
                            ProductName = "Denim Jacket"
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 4,
                            Price = 129,
                            ProductName = "Parka Jacket"
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 4,
                            Price = 69,
                            ProductName = "Windbreaker Jacket"
                        },
                        new
                        {
                            ProductId = 86,
                            CategoryId = 4,
                            Price = 89,
                            ProductName = "Hooded Jacket"
                        },
                        new
                        {
                            ProductId = 87,
                            CategoryId = 4,
                            Price = 159,
                            ProductName = "Trench Coat"
                        },
                        new
                        {
                            ProductId = 88,
                            CategoryId = 4,
                            Price = 139,
                            ProductName = "Peacoat"
                        },
                        new
                        {
                            ProductId = 89,
                            CategoryId = 4,
                            Price = 119,
                            ProductName = "Quilted Jacket"
                        },
                        new
                        {
                            ProductId = 90,
                            CategoryId = 4,
                            Price = 109,
                            ProductName = "Field Jacket"
                        },
                        new
                        {
                            ProductId = 91,
                            CategoryId = 4,
                            Price = 129,
                            ProductName = "Blazer Jacket"
                        },
                        new
                        {
                            ProductId = 92,
                            CategoryId = 4,
                            Price = 149,
                            ProductName = "Suede Jacket"
                        },
                        new
                        {
                            ProductId = 93,
                            CategoryId = 4,
                            Price = 99,
                            ProductName = "Varsity Jacket"
                        },
                        new
                        {
                            ProductId = 94,
                            CategoryId = 4,
                            Price = 79,
                            ProductName = "Cropped Jacket"
                        },
                        new
                        {
                            ProductId = 95,
                            CategoryId = 4,
                            Price = 139,
                            ProductName = "Puffer Jacket"
                        },
                        new
                        {
                            ProductId = 96,
                            CategoryId = 4,
                            Price = 69,
                            ProductName = "Fleece Jacket"
                        },
                        new
                        {
                            ProductId = 97,
                            CategoryId = 4,
                            Price = 89,
                            ProductName = "Track Jacket"
                        },
                        new
                        {
                            ProductId = 98,
                            CategoryId = 4,
                            Price = 119,
                            ProductName = "Military Jacket"
                        },
                        new
                        {
                            ProductId = 99,
                            CategoryId = 4,
                            Price = 79,
                            ProductName = "Rain Jacket"
                        },
                        new
                        {
                            ProductId = 100,
                            CategoryId = 4,
                            Price = 99,
                            ProductName = "Anorak Jacket"
                        },
                        new
                        {
                            ProductId = 101,
                            CategoryId = 4,
                            Price = 169,
                            ProductName = "Shearling Jacket"
                        },
                        new
                        {
                            ProductId = 102,
                            CategoryId = 4,
                            Price = 149,
                            ProductName = "Wool Jacket"
                        },
                        new
                        {
                            ProductId = 103,
                            CategoryId = 4,
                            Price = 89,
                            ProductName = "Coach Jacket"
                        },
                        new
                        {
                            ProductId = 104,
                            CategoryId = 4,
                            Price = 109,
                            ProductName = "Softshell Jacket"
                        },
                        new
                        {
                            ProductId = 105,
                            CategoryId = 4,
                            Price = 119,
                            ProductName = "Canvas Jacket"
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 5,
                            Price = 199,
                            ProductName = "Single-Breasted Suit"
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 5,
                            Price = 249,
                            ProductName = "Double-Breasted Suit"
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 5,
                            Price = 219,
                            ProductName = "Slim Fit Suit"
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 5,
                            Price = 189,
                            ProductName = "Classic Fit Suit"
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 5,
                            Price = 179,
                            ProductName = "Two-Piece Suit"
                        },
                        new
                        {
                            ProductId = 106,
                            CategoryId = 5,
                            Price = 259,
                            ProductName = "Three-Piece Suit"
                        },
                        new
                        {
                            ProductId = 107,
                            CategoryId = 5,
                            Price = 299,
                            ProductName = "Tuxedo Suit"
                        },
                        new
                        {
                            ProductId = 108,
                            CategoryId = 5,
                            Price = 269,
                            ProductName = "Velvet Suit"
                        },
                        new
                        {
                            ProductId = 109,
                            CategoryId = 5,
                            Price = 199,
                            ProductName = "Linen Suit"
                        },
                        new
                        {
                            ProductId = 110,
                            CategoryId = 5,
                            Price = 229,
                            ProductName = "Wool Suit"
                        },
                        new
                        {
                            ProductId = 111,
                            CategoryId = 5,
                            Price = 239,
                            ProductName = "Pinstripe Suit"
                        },
                        new
                        {
                            ProductId = 112,
                            CategoryId = 5,
                            Price = 219,
                            ProductName = "Plaid Suit"
                        },
                        new
                        {
                            ProductId = 113,
                            CategoryId = 5,
                            Price = 249,
                            ProductName = "Herringbone Suit"
                        },
                        new
                        {
                            ProductId = 114,
                            CategoryId = 5,
                            Price = 209,
                            ProductName = "Checked Suit"
                        },
                        new
                        {
                            ProductId = 115,
                            CategoryId = 5,
                            Price = 189,
                            ProductName = "Cotton Suit"
                        },
                        new
                        {
                            ProductId = 116,
                            CategoryId = 5,
                            Price = 179,
                            ProductName = "Casual Suit"
                        },
                        new
                        {
                            ProductId = 117,
                            CategoryId = 5,
                            Price = 299,
                            ProductName = "Black Tie Suit"
                        },
                        new
                        {
                            ProductId = 118,
                            CategoryId = 5,
                            Price = 189,
                            ProductName = "Summer Suit"
                        },
                        new
                        {
                            ProductId = 119,
                            CategoryId = 5,
                            Price = 269,
                            ProductName = "Winter Suit"
                        },
                        new
                        {
                            ProductId = 120,
                            CategoryId = 5,
                            Price = 219,
                            ProductName = "Business Suit"
                        },
                        new
                        {
                            ProductId = 121,
                            CategoryId = 5,
                            Price = 199,
                            ProductName = "Casual Blazer Suit"
                        },
                        new
                        {
                            ProductId = 122,
                            CategoryId = 5,
                            Price = 239,
                            ProductName = "Modern Fit Suit"
                        },
                        new
                        {
                            ProductId = 123,
                            CategoryId = 5,
                            Price = 229,
                            ProductName = "Stretch Suit"
                        },
                        new
                        {
                            ProductId = 124,
                            CategoryId = 5,
                            Price = 279,
                            ProductName = "Zoot Suit"
                        },
                        new
                        {
                            ProductId = 125,
                            CategoryId = 5,
                            Price = 189,
                            ProductName = "Seersucker Suit"
                        });
                });

            modelBuilder.Entity("EF_project.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EF_project.Models.Favorites", b =>
                {
                    b.HasOne("EF_project.Models.Products", "products")
                        .WithMany("favorites")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_project.Models.User", "user")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("products");

                    b.Navigation("user");
                });

            modelBuilder.Entity("EF_project.Models.Products", b =>
                {
                    b.HasOne("EF_project.Models.Categories", "categories")
                        .WithMany("products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categories");
                });

            modelBuilder.Entity("EF_project.Models.Categories", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("EF_project.Models.Products", b =>
                {
                    b.Navigation("favorites");
                });

            modelBuilder.Entity("EF_project.Models.User", b =>
                {
                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
